name: Enable User in Utility
description: Add user in utility allow list
title: "[Add User]: <USER>"
labels: ["onboarding-utility"]
assignees:
  - calquisola
body:
  - type: input
    id: email
    attributes:
      label: User Email(s)
      description: For simplicity, please use the email you used for your login.gov account
      placeholder: ex. me@va.gov, user@va.gov 
    validations:
      required: true
 