name: Enable User
description: Add user in AMT's whitelist
title: "[Add User]: <USER>"
labels: ["onboarding"]
assignees:
  - calquisola
body:
  - type: input
    id: email
    attributes:
      label: User Email
      description: For simplicity, please use the email you used for your login.gov account
      placeholder: ex. me@va.gov, you@test.com
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environment
      description: Which environment do you want to be added?
      multiple: false
      options:
        - Dev
        - Utility
    validations:
      required: true 

