name: Enable User in Dev
description: > 
  This request is intended for Platform team members developing platform tools that authenticate with the Dev instance of Keycloak. 
  If you are a VFS team member, please request access through [this issue template](https://github.com/calquisola/templateTest/issues/new?assignees=calquisola&labels=onboarding-utility&template=add_utility_user.yml&title=%5BAdd+User%5D%3A+%3CUSER%3E)
title: "[Add Developer]: <NAME>"
labels: ["onboarding-dev"]
assignees:
  - calquisola
body:
  - type: input
    id: email
    attributes:
      label: User Email(s)
      description: For simplicity, please use the email you used for your login.gov account
      placeholder: ex. me@va.gov, user@va.gov
    validations:
      required: true
