name: Service Account Request
description: |
  This request allows AMT to set up a service account with strong identity assurance.
title: "[Service Account Request]: "
labels: ["integration", "service account"]
assignees:
  - kjduensing
  - calquisola
  - ken-non
  - kylesoskin
body:
  - type: input
    id: clientId
    attributes:
      label: Service Client ID
      description: The client ID used by your service to make requests to AMS
      placeholder: ex. firebase-clone, my-app, local-app-test-1
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for Request
      description: Please provide the intent with which the service account will be used
    validations:
      required: true
  - type: textarea
    id: publickey
    attributes:
      label: Public Key (PEM format)
      description: A public key tied to your application specifically for the purposes of authentication. This key must be in PEM format
    validations: 
      required: true

