name: Parse Emails in utility and creates a PR
on:
  issues:
    types: [opened]

concurrency: 'main'
jobs:
  place_order:
    if: contains(github.event.issue.labels.*.name, 'onboarding-utility')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Dump GitHub context
        id: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo '$GITHUB_CONTEXT'
          echo '${{ github.actor }}'
          
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_utility_user.yml
      - name: Get emails
        run: | 
            echo '${{ steps.issue-parser.outputs.jsonString }}' > user.json
            cat user.json
      - name: Add emails to the utility list
        run: |
            python scripts/add_user_to_file.py user.json users_utility.txt
            cat users_utility.txt
            echo '${{ github.event.issue.number }}'

      - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                commit-message: added new utility users
                title: '${{ github.event.issue.title }}'
                body: '${{ github.event.issue.body }}' 
                branch: add.utility.user.'${{ github.event.issue.number }}'
            
      