
name: Update dynamodb when a new key is added or removed

on:
  push:
    branches: [ main ]
    paths: 
    - 'users/users_utility.txt'

jobs:
  run:
    name: AMT dynamodb utility workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Parse added users
        run: |
          git show users/users_utility.txt > changes.txt
      - name: Format Json for aws cli
        run: |
          mkdir pst_amt_dynamodb
          cat changes.txt
          python scripts/parse_user_list_changes.py changes.txt users_utility pst_amt_dynamodb
          cat pst_amt_dynamodb/add_user.json
      - name:  Add/Remove DynamoDB Items
        run: |
          aws dynamodb batch-write-item --request-items file://pst_amt_dynamodb/add_user.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1' 



      