
name: Update dynamodb when a new key is added or removed

on:
  push:
    branches: [ main ]
    paths: 
    - 'users_utility.txt'

jobs:
  run:
    name: AMT dynamodb utility workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Parse added users
        run: |
          git show users_utility.txt > changes.txt
      - name: Format Json for aws cli
        run: |
          mkdir pst_amt_dynamodb
          python scripts/parse_user_list_changes.py changes.txt pst_amt_dynamodb
          cat pst_amt_dynamodb/add_user.json


      