name: Process order
on:
  issues:
    types: [opened]

concurrency: 'main'
jobs:
  place_order:
    if: contains(github.event.pull_request.labels.*.name, 'onboarding')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_dev_user.yml
      - run: echo '${{ github.event.label }}' > label.txt
      - run: echo label.txt
      - run: echo '${{  github.event.issue.label }}' > event.json
      - run: cat event.json
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > user.json
      - run: cat user.json
      