name: Process order
on:
  issues:
    types: [opened]

concurrency: 'main'
jobs:
  place_order:
    if: contains(github.event.issue.labels.*.name, 'onboarding')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_dev_user.yml
      - name: Get email
        run: | 
            echo '${{ steps.issue-parser.outputs.jsonString }}' > user.json
            cat user.json
      - name: Format Json for aws cli
        run: |
          mkdir pst_amt_dynamodb
          python scripts/format_request.py user.json pst_amt_dynamodb
          cat pst_amt_dynamodb/add_user.json
      - name:  Add/Remove DynamoDB Items
        run: |
          aws dynamodb batch-write-item --request-items file://pst_amt_dynamodb/add_user.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'    
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Hi! You have been added to our user list.
           
      