name: Process order
on:
  issues:
    types: opened

concurrency: 'main'
jobs:
  place_order:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_dev_user.yml
      - run: echo '${{  github.event.issue.label }}' > event.json
      - run: cat event.json
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > user.json
      - run: cat user.json
      